# Jekyll Resume Theme

# Site settings
title: Résumé
email: danielernesto@ufm.edu
description: Résumé of Daniel Hernández
baseurl: ""
url: "danisnowman.github.io/"
name: Daniel Ernesto Hernández Zelada
job: Computer Science Student
location: Guatemala City, GT
languages: programming, data science, infosec, theology, literature
twitter_username: snowminal
github_username:  Danisnowman
instagram_user:  danisnowman
goodreads_user: danisnowman
linkedin_link: https://www.linkedin.com/in/danisnowman/
blog_link: http://danisnowman.github.io/
email_address: danielernesto@ufm.edu

# Build settings
markdown: kramdown

plugins: 
    - github-pages
