# Jekyll Resume Theme

# Site settings
title: Resumé
email: danielernesto@ufm.edu
description: Jekyll Resume is a mega simple resume theme for Jekyll.
baseurl: ""
url: "http://mattcouchman.co.uk/jekyll-resume"
name: Daniel E. Hernández
job: Computer Science Student
location: Guatemala City, GT
languages: programming, data science, infosec, theology, literature
twitter_username: snowminal
github_username:  Danisnowman
instagram_user:  danisnowman
goodreads_user: danisnowman
linkedin_link: https://www.linkedin.com/in/daniel-hernández-3b8104159/
email_address: danielernesto@ufm.edu

# Build settings
markdown: kramdown

plugins: 
    - github-pages
